spring:
  application:
    name: person-servise
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user1
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
   port: 8890

flyway:
  url: jdbc:mysql://127.0.0.1:3306/user
  username: root
  password: root
  locations: classpath:db/migration


