version: '3.8'
services:
  app:
    build:
      context: ./service/app
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:mysql://mySql/root
      - JS_URL=http://localhost
    image: 'java-application'
    ports:
        - "8080:8080"
    depends_on:
        - mySql

  mySql:
    image: mysql:8.0
    build:
      context: ./service/mySql
      dockerfile: Dockerfile
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
      - MYSQL_USER=artemaverkov
      - MYSQL_PASSWORD=root

