version: '3.8'
services:
  app:
    build:
      context: ./service/app
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/root
      - JS_URL=http://localhost
    ports:
      - "8080:8080"
    depends_on:
         - postgres


  postgres:
    build:
      context: /service/postgres
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=artemaverkov
      - POSTGRES_DB=root
      - POSTGRES_PASSWORD=root

